### ISSUE TITLE
tried running it but handle_connection error 

### ISSUE THREAD

**Issue by AbhimanyuAryan** [emmaccode/JLChat.jl#1] opened 2023-01-29 08:23 UTC
created an empty `public` directory but the I get this error

```
1.8.5>┌ Error: handle_connection handler error
│   exception =
│    MethodError: no method matching style!(::Component{:dialog}, ::Pair{String, String}, ::Pair{String, String}, ::Pair{String, String}, ::Pair{String, String}, ::Pair{String, String}, ::Pair{String, String}, ::Pair{String, String})
│    Closest candidates are:
│      style!(::Component{:sheet}, ::String, ::Pair{String, String}) at C:\Users\aryan\.julia\packages\ToolipsDefaults\79ITl\src\Styles.jl:137
│    Stacktrace:
│     [1] dialog(::Connection, ::String; x::String, y::String, label::String, args::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
│       @ ToolipsDefaults C:\Users\aryan\.julia\packages\ToolipsDefaults\79ITl\src\Components.jl:64
│     [2] home(c::Connection)
│       @ JLChat C:\Users\aryan\Documents\JLChat.jl\src\JLChat.jl:33
│     [3] (::Toolips.var"#serve#61"{Vector{Toolips.AbstractRoute}, String, Vector{ServerExtension}, Vector{ServerExtension}})(http::HTTP.Streams.Stream{HTTP.Messages.Request, HTTP.ConnectionPool.Connection})
│       @ Toolips C:\Users\aryan\.julia\packages\Toolips\TN9Xs\src\server\Core.jl:1397
│     [4] #invokelatest#2
│       @ .\essentials.jl:729 [inlined]
│     [5] invokelatest
│       @ .\essentials.jl:726 [inlined]
│     [6] handle_connection(f::Function, c::HTTP.ConnectionPool.Connection, listener::HTTP.Servers.Listener{Nothing, Sockets.TCPServer}, readtimeout::Int64, access_log::Nothing)
│       @ HTTP.Servers C:\Users\aryan\.julia\packages\HTTP\RQd4C\src\Servers.jl:447
│     [7] (::HTTP.Servers.var"#16#17"{Toolips.var"#serve#61"{Vector{Toolips.AbstractRoute}, String, Vector{ServerExtension}, Vector{ServerExtension}}, HTTP.Servers.Listener{Nothing, Sockets.TCPServer}, Set{HTTP.ConnectionPool.Connection}, Int64, Nothing, Base.Semaphore, HTTP.ConnectionPool.Connection})()
│       @ HTTP.Servers .\task.jl:484
└ @ HTTP.Servers C:\Users\aryan\.julia\packages\HTTP\RQd4C\src\Servers.jl:46
```

**Comment by emmaccode** [comment] 2023-01-29 08:42
hi abhi!
The problem is this app was built for the revision of ToolipsDefaults that is on Unstable (I have yet to finish this package). The same can be said for ToolipsSession as the next release is large and breaking. The `style!` import commit seems to be the most recent commit -- [here](https://github.com/ChifiSource/ToolipsDefaults.jl/commit/760fdc93b4d981cb9a275569e630ddb64153cff6).
So to solve this,
```julia
julia> ;
shell> pwd()
"home/emmac/dev/toolips/JLChat.jl"
julia> ]
pkg> activate .
pkg> rm ToolipsDefaults
pkg> rm ToolipsSession
pkg> add ToolipsSession#Unstable
pkg> add https://github.com/ChifiSource/ToolipsDefaults.jl#Unstable
julia> include("dev.jl")
```
Should all around be pretty simple. Another thing; just for the sake of it this is also deployed, so you can try it out for yourself (on a website with potential other people) [here](https://ems.computer/).

**Comment by emmaccode** [comment] 2023-01-29 08:43
Let me know if with that I am good to close this!

**Comment by AbhimanyuAryan** [comment] 2023-01-29 14:13
ok I have new error stack. You should register packages 🙅🏻‍♂️

```
1.8.5>Pkg.precompile()
Precompiling project...
  ✗ ToolipsDefaults
  ✗ JLChat
  0 dependencies successfully precompiled in 3 seconds. 26 already precompiled.

ERROR: The following 2 direct dependencies failed to precompile:

ToolipsDefaults [1710be6b-e895-498d-ba35-e3ff0dac7995]

Failed to precompile ToolipsDefaults [1710be6b-e895-498d-ba35-e3ff0dac7995] to /Users/abhi/.julia/compiled/v1.8/ToolipsDefaults/jl_thMref.
WARNING: could not import ToolipsSession.InputMap into ToolipsDefaults
ERROR: LoadError: UndefVarError: InputMap not defined
Stacktrace:
 [1] top-level scope
   @ ~/.julia/packages/ToolipsDefaults/YTiJg/src/ToolipsDefaults.jl:24
 [2] include
   @ ./Base.jl:419 [inlined]
 [3] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
   @ Base ./loading.jl:1554
 [4] top-level scope
   @ stdin:1
in expression starting at /Users/abhi/.julia/packages/ToolipsDefaults/YTiJg/src/ToolipsDefaults.jl:1
in expression starting at stdin:1

JLChat [f8aac164-0c6e-4b0f-88ed-c7584ed0bffa]

Failed to precompile JLChat [f8aac164-0c6e-4b0f-88ed-c7584ed0bffa] to /Users/abhi/.julia/compiled/v1.8/JLChat/jl_FHJqj2.
WARNING: could not import ToolipsSession.InputMap into ToolipsDefaults
ERROR: LoadError: UndefVarError: InputMap not defined
Stacktrace:
 [1] top-level scope
   @ ~/.julia/packages/ToolipsDefaults/YTiJg/src/ToolipsDefaults.jl:24
 [2] include
   @ ./Base.jl:419 [inlined]
 [3] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
   @ Base ./loading.jl:1554
 [4] top-level scope
   @ stdin:1
in expression starting at /Users/abhi/.julia/packages/ToolipsDefaults/YTiJg/src/ToolipsDefaults.jl:1
in expression starting at stdin:1
ERROR: LoadError: Failed to precompile ToolipsDefaults [1710be6b-e895-498d-ba35-e3ff0dac7995] to /Users/abhi/.julia/compiled/v1.8/ToolipsDefaults/jl_jGFHUa.
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
    @ Base ./loading.jl:1707
  [3] compilecache
    @ ./loading.jl:1651 [inlined]
  [4] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1337
  [5] _require_prelocked(uuidkey::Base.PkgId)
    @ Base ./loading.jl:1200
  [6] macro expansion
    @ ./loading.jl:1180 [inlined]
  [7] macro expansion
    @ ./lock.jl:223 [inlined]
  [8] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1144
  [9] include
    @ ./Base.jl:419 [inlined]
 [10] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
    @ Base ./loading.jl:1554
 [11] top-level scope
    @ stdin:1
in expression starting at /Users/abhi/Git/JLChat.jl/src/JLChat.jl:1
in expression starting at stdin:1

Stacktrace:
 [1] pkgerror(msg::String)
   @ Pkg.Types ~/.julia/juliaup/julia-1.8.5+0.aarch64.apple.darwin14/share/julia/stdlib/v1.8/Pkg/src/Types.jl:67
 [2] precompile(ctx::Pkg.Types.Context, pkgs::Vector{String}; internal_call::Bool, strict::Bool, warn_loaded::Bool, already_instantiated::Bool, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ Pkg.API ~/.julia/juliaup/julia-1.8.5+0.aarch64.apple.darwin14/share/julia/stdlib/v1.8/Pkg/src/API.jl:1435
 [3] precompile
   @ ~/.julia/juliaup/julia-1.8.5+0.aarch64.apple.darwin14/share/julia/stdlib/v1.8/Pkg/src/API.jl:1072 [inlined]
 [4] #precompile#225
   @ ~/.julia/juliaup/julia-1.8.5+0.aarch64.apple.darwin14/share/julia/stdlib/v1.8/Pkg/src/API.jl:1071 [inlined]
 [5] precompile (repeats 2 times)
   @ ~/.julia/juliaup/julia-1.8.5+0.aarch64.apple.darwin14/share/julia/stdlib/v1.8/Pkg/src/API.jl:1071 [inlined]
 [6] top-level scope
   @ REPL[20]:1

1.8.5>
```

my env 

```
(JLChat) pkg> st
Project JLChat v0.1.0
Status `~/Git/JLChat.jl/Project.toml`
⌃ [295af30f] Revise v3.4.0
  [a47e2ad8] Toolips v0.2.2 `~/.julia/dev/Toolips`
  [1710be6b] ToolipsDefaults v0.1.0 `https://github.com/ChifiSource/ToolipsDefaults.jl#Unstable`
  [2fe55384] ToolipsSession v0.3.0 `https://github.com/ChifiSource/ToolipsSession.jl.git#Unstable`
Info Packages marked with ⌃ have new versions available and may be upgradable.
```

Let me know what am I doing wrong. Thanks

**Comment by AbhimanyuAryan** [comment] 2023-01-29 14:24
ok I dev'ed all and I am on `Unstable` branch for Defaults and Session.

```
1.8.5>Pkg.precompile()
Precompiling project...
  ✗ ToolipsDefaults
  ✗ JLChat
  2 dependencies successfully precompiled in 3 seconds. 24 already precompiled.

ERROR: The following 2 direct dependencies failed to precompile:

ToolipsDefaults [1710be6b-e895-498d-ba35-e3ff0dac7995]

Failed to precompile ToolipsDefaults [1710be6b-e895-498d-ba35-e3ff0dac7995] to /Users/abhi/.julia/compiled/v1.8/ToolipsDefaults/jl_d6mwEq.
WARNING: could not import ToolipsSession.InputMap into ToolipsDefaults
ERROR: LoadError: UndefVarError: InputMap not defined
Stacktrace:
 [1] top-level scope
   @ ~/.julia/dev/ToolipsDefaults/src/ToolipsDefaults.jl:24
 [2] include
   @ ./Base.jl:419 [inlined]
 [3] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
   @ Base ./loading.jl:1554
 [4] top-level scope
   @ stdin:1
in expression starting at /Users/abhi/.julia/dev/ToolipsDefaults/src/ToolipsDefaults.jl:1
in expression starting at stdin:1

JLChat [f8aac164-0c6e-4b0f-88ed-c7584ed0bffa]

Failed to precompile JLChat [f8aac164-0c6e-4b0f-88ed-c7584ed0bffa] to /Users/abhi/.julia/compiled/v1.8/JLChat/jl_jcwGDd.
WARNING: could not import ToolipsSession.InputMap into ToolipsDefaults
ERROR: LoadError: UndefVarError: InputMap not defined
Stacktrace:
 [1] top-level scope
   @ ~/.julia/dev/ToolipsDefaults/src/ToolipsDefaults.jl:24
 [2] include
   @ ./Base.jl:419 [inlined]
 [3] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
   @ Base ./loading.jl:1554
 [4] top-level scope
   @ stdin:1
in expression starting at /Users/abhi/.julia/dev/ToolipsDefaults/src/ToolipsDefaults.jl:1
in expression starting at stdin:1
ERROR: LoadError: Failed to precompile ToolipsDefaults [1710be6b-e895-498d-ba35-e3ff0dac7995] to /Users/abhi/.julia/compiled/v1.8/ToolipsDefaults/jl_C94PcU.
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
    @ Base ./loading.jl:1707
  [3] compilecache
    @ ./loading.jl:1651 [inlined]
  [4] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1337
  [5] _require_prelocked(uuidkey::Base.PkgId)
    @ Base ./loading.jl:1200
  [6] macro expansion
    @ ./loading.jl:1180 [inlined]
  [7] macro expansion
    @ ./lock.jl:223 [inlined]
  [8] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1144
  [9] include
    @ ./Base.jl:419 [inlined]
 [10] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
    @ Base ./loading.jl:1554
 [11] top-level scope
    @ stdin:1
in expression starting at /Users/abhi/Git/JLChat.jl/src/JLChat.jl:1
in expression starting at stdin:1

Stacktrace:
 [1] pkgerror(msg::String)
   @ Pkg.Types ~/.julia/juliaup/julia-1.8.5+0.aarch64.apple.darwin14/share/julia/stdlib/v1.8/Pkg/src/Types.jl:67
 [2] precompile(ctx::Pkg.Types.Context, pkgs::Vector{String}; internal_call::Bool, strict::Bool, warn_loaded::Bool, already_instantiated::Bool, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ Pkg.API ~/.julia/juliaup/julia-1.8.5+0.aarch64.apple.darwin14/share/julia/stdlib/v1.8/Pkg/src/API.jl:1435
 [3] precompile
   @ ~/.julia/juliaup/julia-1.8.5+0.aarch64.apple.darwin14/share/julia/stdlib/v1.8/Pkg/src/API.jl:1072 [inlined]
 [4] #precompile#225
   @ ~/.julia/juliaup/julia-1.8.5+0.aarch64.apple.darwin14/share/julia/stdlib/v1.8/Pkg/src/API.jl:1071 [inlined]
 [5] precompile (repeats 2 times)
   @ ~/.julia/juliaup/julia-1.8.5+0.aarch64.apple.darwin14/share/julia/stdlib/v1.8/Pkg/src/API.jl:1071 [inlined]
 [6] top-level scope
   @ REPL[4]:1

1.8.5>

```

but I get this error :(

**Comment by emmaccode** [comment] 2023-01-29 21:22
agh I made some updates last night using my local version of ToolipsSession, ToolipsSession Unstable updated to facilitate the `AbstracInputMap` -> `InputMap` change.
```julia
using Pkg; Pkg.update()
```
The good news is these are both really close to being finished with the commits I added last night! (Let me know if this works for you, as it should.)

**Comment by AbhimanyuAryan** [comment] 2023-01-30 02:59
ok interesting

```
[ Info: Listening on: 127.0.0.1:8000
37;1m[2023:01:30:02:58]: 🌷 toolips> server started at: http://127.0.0.1:8000

WebServer
hosted at: http://127.0.0.1:8000
status: 4
    routes
    /
404
/modifier/linker

    extensions
    Logger
Files
ToolipsSession.Session


1.8.5>┌ Error: handle_connection handler error
│   exception =
│    MethodError: Cannot `convert` an object of type
│      Component{namedialog} to an object of type
│      Component{dialog}
│    Closest candidates are:
│      convert(::Type{T}, ::T) where T at Base.jl:61
│    Stacktrace:
│     [1] dialog(::Connection, ::String; x::String, y::String, label::String, args::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
│       @ ToolipsDefaults C:\Users\aryan\.julia\dev\ToolipsDefaults\src\Components.jl:77
│     [2] home(c::Connection)
│       @ JLChat C:\Users\aryan\Documents\JLChat.jl\src\JLChat.jl:33
│     [3] (::Toolips.var"#serve#61"{Vector{Toolips.AbstractRoute}, String, Vector{ServerExtension}, Vector{ServerExtension}})(http::HTTP.Streams.Stream{HTTP.Messages.Request, HTTP.ConnectionPool.Connection})
│       @ Toolips C:\Users\aryan\.julia\dev\Toolips\src\server\Core.jl:1423
│     [4] #invokelatest#2
│       @ .\essentials.jl:729 [inlined]
│     [5] invokelatest
│       @ .\essentials.jl:726 [inlined]
│     [6] handle_connection(f::Function, c::HTTP.ConnectionPool.Connection, listener::HTTP.Servers.Listener{Nothing, Sockets.TCPServer}, readtimeout::Int64, access_log::Nothing)
│       @ HTTP.Servers C:\Users\aryan\.julia\packages\HTTP\RQd4C\src\Servers.jl:447
│     [7] (::HTTP.Servers.var"#16#17"{Toolips.var"#serve#61"{Vector{Toolips.AbstractRoute}, String, Vector{ServerExtension}, Vector{ServerExtension}}, HTTP.Servers.Listener{Nothing, Sockets.TCPServer}, Set{HTTP.ConnectionPool.Connection}, Int64, Nothing, Base.Semaphore, HTTP.ConnectionPool.Connection})()
│       @ HTTP.Servers .\task.jl:484
└ @ HTTP.Servers C:\Users\aryan\.julia\packages\HTTP\RQd4C\src\Servers.jl:461
```

**Comment by emmaccode** [comment] 2023-01-30 03:11
Agh, i'm sorry -- I am actively developing that package in particular -- and `ToolipsSession` as we speak, trying to get a new version and the initial version of the other rolled out. I just fixed this bug, but before I send off I am going to git a clone of this and try it myself.

**Comment by AbhimanyuAryan** [comment] 2023-01-30 03:17
no problem @emmettgb :)

**Comment by emmaccode** [comment] 2023-01-30 03:24
That should do it I think! Worked for me!

**Comment by AbhimanyuAryan** [comment] 2023-01-30 13:24
thanks @emmettgb it worked but I also see this error in terminal in `loop`. Keep going in loop

```
1.8.5>include("dev.jl")
  Activating project at `~/Git/JLChat.jl`
[ Info: Precompiling JLChat [f8aac164-0c6e-4b0f-88ed-c7584ed0bffa]
[ Info: Listening on: 127.0.0.1:8000, thread id: 1
37;1m[2023:01:30:18:52]: 🌷 toolips> server started at: http://127.0.0.1:8000

WebServer
hosted at: http://127.0.0.1:8000
status: 4
    routes
    /
404
/modifier/linker

    extensions
    Logger
Files
ToolipsSession.Session


1.8.5>┌ Error: handle_connection handler error
│   exception =
│    Server never wrote a response
│    Stacktrace:
│     [1] error(s::String)
│       @ Base ./error.jl:35
│     [2] handle_connection(f::Function, c::HTTP.ConnectionPool.Connection{Sockets.TCPSocket}, listener::HTTP.Servers.Listener{Nothing, Sockets.TCPServer}, readtimeout::Int64, access_log::Nothing)
│       @ HTTP.Servers ~/.julia/packages/HTTP/z8l0i/src/Servers.jl:450
│     [3] (::HTTP.Servers.var"#16#17"{Toolips.var"#serve#61"{Vector{Toolips.AbstractRoute}, String, Vector{ServerExtension}, Vector{ServerExtension}}, HTTP.Servers.Listener{Nothing, Sockets.TCPServer}, Set{HTTP.ConnectionPool.Connection}, Int64, Nothing, Base.Semaphore, HTTP.ConnectionPool.Connection{Sockets.TCPSocket}})()
│       @ HTTP.Servers ./task.jl:484
└ @ HTTP.Servers ~/.julia/packages/HTTP/z8l0i/src/Servers.jl:461
```

**Comment by emmaccode** [comment] 2023-01-30 13:57
No biggy -- just means some request was sent to the server that the server did not need to respond to, certainly happens from time to time -- though I am not sure why this would be happening on loop, unless you had started the server with a window of a prior session open in your web-browser. Still though -- not too important, I will close :) glad you were able to get it working!

**Closed as completed by emmaccode** 2023-01-30 13:57 UTC

**Comment by AbhimanyuAryan** [comment] 2023-01-30 14:12
@emmettgb awesome. Thanks
